### ISSUE TITLE
notifications generate errors

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/tag_tools#10]
i have been seeing some notifications of internal server errors after adding new videolist videos to my (elgg 2.1) site - since the error message only mentions tag tools, i think the error is caused by the notification that tag tools is generating. this is the error dump i see:

```
    Call to undefined method ElggRelationship::getContainerGUID()

    Error Object
(
    [message:protected] =&gt; Call to undefined method ElggRelationship::getContainerGUID()
    [string:Error:private] =&gt; Error: Call to undefined method ElggRelationship::getContainerGUID() in /mysite/vendor/elgg/elgg/engine/classes/Elgg/Notifications/SubscriptionsService.php:66
Stack trace:
#0 /mysite/vendor/elgg/elgg/engine/classes/Elgg/Notifications/NotificationsService.php(209): Elgg\Notifications\SubscriptionsService-&gt;getSubscriptions(Object(Elgg\Notifications\Event))
#1 /mysite/vendor/elgg/elgg/engine/lib/notification.php(188): Elgg\Notifications\NotificationsService-&gt;processQueue(1472670047)
#2 [internal function]: _elgg_notifications_cron(&#039;cron&#039;, &#039;minute&#039;, &#039;&#039;, Array)
#3 /mysite/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(38): call_user_func_array(&#039;_elgg_notificat...&#039;, Array)
#4 /mysite/vendor/elgg/elgg/engine/lib/elgglib.php(815): Elgg\PluginHooksService-&gt;trigger(&#039;cron&#039;, &#039;minute&#039;, Array, &#039;&#039;)
#5 /mysite/vendor/elgg/elgg/engine/lib/cron.php(122): elgg_trigger_plugin_hook(&#039;cron&#039;, &#039;minute&#039;, Array, &#039;&#039;)
#6 [internal function]: _elgg_cron_page_handler(Array, &#039;cron&#039;)
#7 /mysite/vendor/elgg/elgg/engine/classes/Elgg/Router.php(95): call_user_func(&#039;_elgg_cron_page...&#039;, Array, &#039;cron&#039;)
#8 /mysite/vendor/elgg/elgg/engine/classes/Elgg/Application.php(428): Elgg\Router-&gt;route(Object(Elgg\Http\Request))
#9 /mysite/vendor/elgg/elgg/engine/classes/Elgg/Application.php(371): Elgg\Application-&gt;run()
#10 /mysite/index.php(8): Elgg\Application::index()
#11 {main}
    [code:protected] =&gt; 0
    [file:protected] =&gt; /mysite/vendor/elgg/elgg/engine/classes/Elgg/Notifications/SubscriptionsService.php
    [line:protected] =&gt; 66
    [trace:Error:private] =&gt; Array
        (
            [0] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/classes/Elgg/Notifications/NotificationsService.php
                    [line] =&gt; 209
                    [function] =&gt; getSubscriptions
                    [class] =&gt; Elgg\Notifications\SubscriptionsService
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; Elgg\Notifications\Event Object
                                (
                                    [action:protected] =&gt; create
                                    [object_type:protected] =&gt; relationship
                                    [object_subtype:protected] =&gt; tag_tools:notification
                                    [object_id:protected] =&gt; 121282
                                    [actor_guid:protected] =&gt; 2
                                )

                        )

                )

            [1] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/lib/notification.php
                    [line] =&gt; 188
                    [function] =&gt; processQueue
                    [class] =&gt; Elgg\Notifications\NotificationsService
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; 1472670047
                        )

                )

            [2] =&gt; Array
                (
                    [function] =&gt; _elgg_notifications_cron
                    [args] =&gt; Array
                        (
                            [0] =&gt; cron
                            [1] =&gt; minute
                            [2] =&gt; 
                            [3] =&gt; Array
                                (
                                    [time] =&gt; 1472670002
                                )

                        )

                )

            [3] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php
                    [line] =&gt; 38
                    [function] =&gt; call_user_func_array
                    [args] =&gt; Array
                        (
                            [0] =&gt; _elgg_notifications_cron
                            [1] =&gt; Array
                                (
                                    [0] =&gt; cron
                                    [1] =&gt; minute
                                    [2] =&gt; 
                                    [3] =&gt; Array
                                        (
                                            [time] =&gt; 1472670002
                                        )

                                )

                        )

                )

            [4] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/lib/elgglib.php
                    [line] =&gt; 815
                    [function] =&gt; trigger
                    [class] =&gt; Elgg\PluginHooksService
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; cron
                            [1] =&gt; minute
                            [2] =&gt; Array
                                (
                                    [time] =&gt; 1472670002
                                )

                            [3] =&gt; 
                        )

                )

            [5] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/lib/cron.php
                    [line] =&gt; 122
                    [function] =&gt; elgg_trigger_plugin_hook
                    [args] =&gt; Array
                        (
                            [0] =&gt; cron
                            [1] =&gt; minute
                            [2] =&gt; Array
                                (
                                    [time] =&gt; 1472670002
                                )

                            [3] =&gt; 
                        )

                )

            [6] =&gt; Array
                (
                    [function] =&gt; _elgg_cron_page_handler
                    [args] =&gt; Array
                        (
                            [0] =&gt; Array
                                (
                                    [0] =&gt; minute
                                )

                            [1] =&gt; cron
                        )

                )

            [7] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/classes/Elgg/Router.php
                    [line] =&gt; 95
                    [function] =&gt; call_user_func
                    [args] =&gt; Array
                        (
                            [0] =&gt; _elgg_cron_page_handler
                            [1] =&gt; Array
                                (
                                    [0] =&gt; minute
                                )

                            [2] =&gt; cron
                        )

                )

            [8] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/classes/Elgg/Application.php
                    [line] =&gt; 428
                    [function] =&gt; route
                    [class] =&gt; Elgg\Router
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; Elgg\Http\Request Object
                                (
                                    [attributes] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [request] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [query] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [__elgg_uri] =&gt; /cron/minute
                                                )

                                        )

                                    [server] =&gt; Symfony\Component\HttpFoundation\ServerBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [USER] =&gt; nginx
                                                    [HOME] =&gt; /var/lib/nginx
                                                    [HTTP_CONNECTION] =&gt; Keep-Alive
                                                    [HTTP_HOST] =&gt; www.ureka.org
                                                    [HTTP_ACCEPT_ENCODING] =&gt; identity
                                                    [HTTP_ACCEPT] =&gt; */*
                                                    [HTTP_USER_AGENT] =&gt; Mozilla
                                                    [SCRIPT_FILENAME] =&gt; /mysite/index.php
                                                    [REDIRECT_STATUS] =&gt; 200
                                                    [SERVER_NAME] =&gt; www.mysite.org
                                                    [SERVER_PORT] =&gt; 443
                                                    [SERVER_ADDR] =&gt; 185.53.130.22
                                                    [REMOTE_PORT] =&gt; 52327
                                                    [REMOTE_ADDR] =&gt; 185.53.130.22
                                                    [SERVER_SOFTWARE] =&gt; nginx/1.10.1
                                                    [GATEWAY_INTERFACE] =&gt; CGI/1.1
                                                    [HTTPS] =&gt; on
                                                    [SERVER_PROTOCOL] =&gt; HTTP/1.1
                                                    [DOCUMENT_ROOT] =&gt; /mysite
                                                    [DOCUMENT_URI] =&gt; /cron/minute/
                                                    [REQUEST_URI] =&gt; /cron/minute/
                                                    [SCRIPT_NAME] =&gt; /index.php
                                                    [CONTENT_LENGTH] =&gt; 
                                                    [CONTENT_TYPE] =&gt; 
                                                    [REQUEST_METHOD] =&gt; HEAD
                                                    [QUERY_STRING] =&gt; __elgg_uri=/cron/minute/&amp;
                                                    [FCGI_ROLE] =&gt; RESPONDER
                                                    [PHP_SELF] =&gt; /index.php
                                                    [REQUEST_TIME_FLOAT] =&gt; 1472670002.562
                                                    [REQUEST_TIME] =&gt; 1472670002
                                                )

                                        )

                                    [files] =&gt; Symfony\Component\HttpFoundation\FileBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [cookies] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [headers] =&gt; Symfony\Component\HttpFoundation\HeaderBag Object
                                        (
                                            [headers:protected] =&gt; Array
                                                (
                                                    [connection] =&gt; Array
                                                        (
                                                            [0] =&gt; Keep-Alive
                                                        )

                                                    [host] =&gt; Array
                                                        (
                                                            [0] =&gt; www.mysite.org
                                                        )

                                                    [accept-encoding] =&gt; Array
                                                        (
                                                            [0] =&gt; identity
                                                        )

                                                    [accept] =&gt; Array
                                                        (
                                                            [0] =&gt; */*
                                                        )

                                                    [user-agent] =&gt; Array
                                                        (
                                                            [0] =&gt; Mozilla
                                                        )

                                                    [content-length] =&gt; Array
                                                        (
                                                            [0] =&gt; 
                                                        )

                                                    [content-type] =&gt; Array
                                                        (
                                                            [0] =&gt; 
                                                        )

                                                )

                                            [cacheControl:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [content:protected] =&gt; 
                                    [languages:protected] =&gt; 
                                    [charsets:protected] =&gt; 
                                    [encodings:protected] =&gt; 
                                    [acceptableContentTypes:protected] =&gt; 
                                    [pathInfo:protected] =&gt; 
                                    [requestUri:protected] =&gt; /cron/minute/
                                    [baseUrl:protected] =&gt; 
                                    [basePath:protected] =&gt; 
                                    [method:protected] =&gt; 
                                    [format:protected] =&gt; 
                                    [session:protected] =&gt; 
                                    [locale:protected] =&gt; 
                                    [defaultLocale:protected] =&gt; en
                                )

                        )

                )

            [9] =&gt; Array
                (
                    [file] =&gt; /mysite/vendor/elgg/elgg/engine/classes/Elgg/Application.php
                    [line] =&gt; 371
                    [function] =&gt; run
                    [class] =&gt; Elgg\Application
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [10] =&gt; Array
                (
                    [file] =&gt; /mysite/index.php
                    [line] =&gt; 8
                    [function] =&gt; index
                    [class] =&gt; Elgg\Application
                    [type] =&gt; ::
                    [args] =&gt; Array
                        (
                        )

                )

        )

    [previous:Error:private] =&gt; 
)
```

**Comment by jdalsem** [comment]
This was fixed long ago in core https://github.com/Elgg/Elgg/commit/65be05c567692694e052ae4711450b7c19f2d571
