### ISSUE TITLE
Tag Tools does not allows to run daily cron 

### ISSUE THREAD

**Issue by merilturock** [ColdTrick/tag_tools#14]
I get the following error for daily cron but if i disable Tag Tools i don't have the problem.

```
Secondary loader failed to return row for 298719

        IncompleteEntityException Object
(
    [message:protected] =&gt; Secondary loader failed to return row for 298719
    [string:Exception:private] =&gt; exception &#039;IncompleteEntityException&#039; with message &#039;Secondary loader failed to return row for 298719&#039; in /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/AttributeLoader.php:235
Stack trace:
#0 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggObject.php(103): Elgg\AttributeLoader-&gt;getRequiredAttributes(Object(stdClass))
#1 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggObject.php(74): ElggObject-&gt;load(Object(stdClass))
#2 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php(276): ElggObject-&gt;__construct(Object(stdClass))
#3 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php(347): Elgg\Database\EntityTable-&gt;rowToElggStar(Object(stdClass))
#4 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/lib/entities.php(205): Elgg\Database\EntityTable-&gt;get(&#039;298719&#039;)
#5 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggExtender.php(164): get_entity(&#039;298719&#039;)
#6 /home/websiteplatfrom/public_html/mod/tag_tools/classes/ColdTrick/TagTools/Rules.php(45): ElggExtender-&gt;getEntity()
#7 [internal function]: ColdTrick\TagTools\Rules::applyRules(&#039;create&#039;, &#039;metadata&#039;, Object(ElggMetadata))
#8 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/EventsService.php(113): call_user_func_array(&#039;\\ColdTrick\\TagT...&#039;, Array)
#9 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/MetadataTable.php(188): Elgg\EventsService-&gt;trigger(&#039;create&#039;, &#039;metadata&#039;, Object(ElggMetadata))
#10 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php(448): Elgg\Database\MetadataTable-&gt;create(298719, &#039;tags&#039;, &#039;movies&#039;, &#039;&#039;, 8316, 2, true)
#11 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php(223): ElggEntity-&gt;setMetadata(&#039;tags&#039;, Array)
#12 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php(1586): ElggEntity-&gt;__set(&#039;tags&#039;, Array)
#13 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggObject.php(120): ElggEntity-&gt;create()
#14 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php(1452): ElggObject-&gt;create()
#15 /home/websiteplatfrom/public_html/mod/rssimport/classes/AU/RSSImport/RSSImport.php(554): ElggEntity-&gt;save()
#16 /home/websiteplatfrom/public_html/mod/rssimport/classes/AU/RSSImport/RSSImport.php(217): AU\RSSImport\RSSImport-&gt;importBlog(Object(SimplePie_Item))
#17 /home/websiteplatfrom/public_html/mod/rssimport/lib/functions.php(115): AU\RSSImport\RSSImport-&gt;importItem(Object(SimplePie_Item))
#18 /home/websiteplatfrom/public_html/mod/rssimport/lib/hooks.php(29): AU\RSSImport\cron_import(&#039;daily&#039;)
#19 [internal function]: AU\RSSImport\daily_cron(&#039;cron&#039;, &#039;daily&#039;, &#039;&#039;, Array)
#20 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(52): call_user_func_array(&#039;AU\\RSSImport\\da...&#039;, Array)
#21 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/lib/elgglib.php(827): Elgg\PluginHooksService-&gt;trigger(&#039;cron&#039;, &#039;daily&#039;, Array, &#039;&#039;)
#22 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/lib/cron.php(133): elgg_trigger_plugin_hook(&#039;cron&#039;, &#039;daily&#039;, Array, &#039;&#039;)
#23 [internal function]: _elgg_cron_page_handler(Array, &#039;cron&#039;)
#24 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(100): call_user_func(&#039;_elgg_cron_page...&#039;, Array, &#039;cron&#039;)
#25 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(436): Elgg\Router-&gt;route(Object(Elgg\Http\Request))
#26 /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(384): Elgg\Application-&gt;run()
#27 /home/websiteplatfrom/public_html/index.php(8): Elgg\Application::index()
#28 {main}
    [code:protected] =&gt; 0
    [file:protected] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/AttributeLoader.php
    [line:protected] =&gt; 235
    [trace:Exception:private] =&gt; Array
        (
            [0] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggObject.php
                    [line] =&gt; 103
                    [function] =&gt; getRequiredAttributes
                    [class] =&gt; Elgg\AttributeLoader
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 298719
                                    [type] =&gt; object
                                    [subtype] =&gt; 4
                                    [owner_guid] =&gt; 8316
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 8316
                                    [access_id] =&gt; 2
                                    [time_created] =&gt; 1507897922
                                    [time_updated] =&gt; 1507897922
                                    [last_action] =&gt; 1507897922
                                    [enabled] =&gt; yes
                                )

                        )

                )

            [1] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggObject.php
                    [line] =&gt; 74
                    [function] =&gt; load
                    [class] =&gt; ElggObject
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 298719
                                    [type] =&gt; object
                                    [subtype] =&gt; 4
                                    [owner_guid] =&gt; 8316
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 8316
                                    [access_id] =&gt; 2
                                    [time_created] =&gt; 1507897922
                                    [time_updated] =&gt; 1507897922
                                    [last_action] =&gt; 1507897922
                                    [enabled] =&gt; yes
                                )

                        )

                )

            [2] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php
                    [line] =&gt; 276
                    [function] =&gt; __construct
                    [class] =&gt; ElggObject
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 298719
                                    [type] =&gt; object
                                    [subtype] =&gt; 4
                                    [owner_guid] =&gt; 8316
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 8316
                                    [access_id] =&gt; 2
                                    [time_created] =&gt; 1507897922
                                    [time_updated] =&gt; 1507897922
                                    [last_action] =&gt; 1507897922
                                    [enabled] =&gt; yes
                                )

                        )

                )

            [3] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php
                    [line] =&gt; 347
                    [function] =&gt; rowToElggStar
                    [class] =&gt; Elgg\Database\EntityTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 298719
                                    [type] =&gt; object
                                    [subtype] =&gt; 4
                                    [owner_guid] =&gt; 8316
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 8316
                                    [access_id] =&gt; 2
                                    [time_created] =&gt; 1507897922
                                    [time_updated] =&gt; 1507897922
                                    [last_action] =&gt; 1507897922
                                    [enabled] =&gt; yes
                                )

                        )

                )

            [4] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/lib/entities.php
                    [line] =&gt; 205
                    [function] =&gt; get
                    [class] =&gt; Elgg\Database\EntityTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; 298719
                        )

                )

            [5] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggExtender.php
                    [line] =&gt; 164
                    [function] =&gt; get_entity
                    [args] =&gt; Array
                        (
                            [0] =&gt; 298719
                        )

                )

            [6] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/mod/tag_tools/classes/ColdTrick/TagTools/Rules.php
                    [line] =&gt; 45
                    [function] =&gt; getEntity
                    [class] =&gt; ElggExtender
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [7] =&gt; Array
                (
                    [function] =&gt; applyRules
                    [class] =&gt; ColdTrick\TagTools\Rules
                    [type] =&gt; ::
                    [args] =&gt; Array
                        (
                            [0] =&gt; create
                            [1] =&gt; metadata
                            [2] =&gt; ElggMetadata Object
                                (
                                    [attributes:protected] =&gt; Array
                                        (
                                            [time_created] =&gt; 1507897922
                                            [type] =&gt; metadata
                                            [id] =&gt; 2534861
                                            [entity_guid] =&gt; 298719
                                            [owner_guid] =&gt; 8316
                                            [access_id] =&gt; 2
                                            [enabled] =&gt; yes
                                            [name_id] =&gt; 60
                                            [value_id] =&gt; 61992
                                            [value_type] =&gt; text
                                            [name] =&gt; tags
                                            [value] =&gt; movies
                                        )

                                    [valid:protected] =&gt;
                                    [time:ElggData:private] =&gt;
                                )

                        )

                )

            [8] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/EventsService.php
                    [line] =&gt; 113
                    [function] =&gt; call_user_func_array
                    [args] =&gt; Array
                        (
                            [0] =&gt; \ColdTrick\TagTools\Rules::applyRules
                            [1] =&gt; Array
                                (
                                    [0] =&gt; create
                                    [1] =&gt; metadata
                                    [2] =&gt; ElggMetadata Object
                                        (
                                            [attributes:protected] =&gt; Array
                                                (
                                                    [time_created] =&gt; 1507897922
                                                    [type] =&gt; metadata
                                                    [id] =&gt; 2534861
                                                    [entity_guid] =&gt; 298719
                                                    [owner_guid] =&gt; 8316
                                                    [access_id] =&gt; 2
                                                    [enabled] =&gt; yes
                                                    [name_id] =&gt; 60
                                                    [value_id] =&gt; 61992
                                                    [value_type] =&gt; text
                                                    [name] =&gt; tags
                                                    [value] =&gt; movies
                                                )

                                            [valid:protected] =&gt;
                                            [time:ElggData:private] =&gt;
                                        )

                                )

                        )

                )

            [9] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/MetadataTable.php
                    [line] =&gt; 188
                    [function] =&gt; trigger
                    [class] =&gt; Elgg\EventsService
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; create
                            [1] =&gt; metadata
                            [2] =&gt; ElggMetadata Object
                                (
                                    [attributes:protected] =&gt; Array
                                        (
                                            [time_created] =&gt; 1507897922
                                            [type] =&gt; metadata
                                            [id] =&gt; 2534861
                                            [entity_guid] =&gt; 298719
                                            [owner_guid] =&gt; 8316
                                            [access_id] =&gt; 2
                                            [enabled] =&gt; yes
                                            [name_id] =&gt; 60
                                            [value_id] =&gt; 61992
                                            [value_type] =&gt; text
                                            [name] =&gt; tags
                                            [value] =&gt; movies
                                        )

                                    [valid:protected] =&gt;
                                    [time:ElggData:private] =&gt;
                                )

                        )

                )

            [10] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php
                    [line] =&gt; 448
                    [function] =&gt; create
                    [class] =&gt; Elgg\Database\MetadataTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; 298719
                            [1] =&gt; tags
                            [2] =&gt; movies
                            [3] =&gt;
                            [4] =&gt; 8316
                            [5] =&gt; 2
                            [6] =&gt; 1
                        )

                )

            [11] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php
                    [line] =&gt; 223
                    [function] =&gt; setMetadata
                    [class] =&gt; ElggEntity
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; tags
                            [1] =&gt; Array
                                (
                                    [0] =&gt; movies
                                    [1] =&gt; movie review
                                )

                        )

                )

            [12] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php
                    [line] =&gt; 1586
                    [function] =&gt; __set
                    [class] =&gt; ElggEntity
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; tags
                            [1] =&gt; Array
                                (
                                    [0] =&gt; movies
                                    [1] =&gt; movie review
                                )

                        )

                )

            [13] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggObject.php
                    [line] =&gt; 120
                    [function] =&gt; create
                    [class] =&gt; ElggEntity
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [14] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php
                    [line] =&gt; 1452
                    [function] =&gt; create
                    [class] =&gt; ElggObject
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [15] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/mod/rssimport/classes/AU/RSSImport/RSSImport.php
                    [line] =&gt; 554
                    [function] =&gt; save
                    [class] =&gt; ElggEntity
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [16] =&gt; Array
                (
                    [file] =&gt; /home/websiteplatfrom/public_html/mod/rssimport/classes/AU/RSSImport/RSSImport.php
                    [line] =&gt; 217
                    [function] =&gt; importBlog
                    [class] =&gt; AU\RSSImport\RSSImport
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; SimplePie_Item Object
                                (
                                    [feed] =&gt; SimplePie Object
                                        (
                                            [data] =&gt; Array
                                                (
                                                    [child] =&gt; Array
                                                        (
                                                            [http://www.w3.org/2005/Atom] =&gt; Array
                                                                (
                                                                    [feed] =&gt; Array
                                                                        (
                                                                            [0] =&gt; Array
                                                                                (
                                                                                    [data] =&gt;
```

**Comment by merilturock** [comment]
[internal function]: ColdTrick\TagTools\Rules::applyRules(&#039;create&#039;, &#039;metadata&#039;, Object(ElggMetadata))

Can i just know why the updated TagTools fails when running daily cron job where this is the error i get when i have not created any kind of rules for it ?? as it keeps failing with RSS import ..

**Comment by merilturock** [comment]
Is there anyway that i can cancel all the tag suggest at one click ??

**Comment by merilturock** [comment]
Is there a way where i can disable the tag rules ??

**Comment by jeabakker** [comment]
> Can i just know why the updated TagTools fails when running daily cron job where this is the error i get when i have not created any kind of rules for it ?? as it keeps failing with RSS import

Somehow this fails in getting the entity of the metadata (just before we check it there are any tag rules).

> Is there a way where i can disable the tag rules ??

you could unregister the tag rules event https://github.com/ColdTrick/tag_tools/blob/884361afa3fd3501c4dba315cc958bb4f0f6e437/start.php#L40

Not sure is this is an issue in Tag Tools or something in rssimport
